<a href="https://colab.research.google.com/github/Gurmeet-byte/Gurmeet-byte/blob/main/imbalancedata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [3]:
movies = pd.read_csv('top10K-TMDB-movies.csv')


# New Section

In [4]:
movies.head()


id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi   
2    238                The Godfather           Drama,Crime                en   
3    424             Schindler's List     Drama,History,War                en   
4    240       The Godfather: Part II           Drama,Crime                en   

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23   
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19   
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14   
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15   
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20   

   vote_average  vote_count  
0           8.7       21862  
1           8.7        3731  
2           8.7       16280  
3           8.6       12959  
4           8.6        9811

In [5]:
print(movies.columns)


Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')


In [6]:
movies = movies[['id', 'title', 'genre', 'overview']]



In [7]:
movies



id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 genre  \
0                                          Drama,Crime   
1                                 Comedy,Drama,Romance   
2                                          Drama,Crime   
3                                    Drama,History,War   
4                                          Drama,Crime   
...                                                ...   
9995                          Action,Adventure,Fantasy   
9996  Action,TV Movie,Science Fiction,Comedy,Adventure   
9997                        Action,Science Fiction,War   
9998                    Adventure,Fantasy,Action,Drama   
9999                             Thriller,Action,Crime   

                                               overview  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 4 columns]

In [8]:
movies['tags'] = movies['overview'] + movies['genre']


<ipython-input-8-5313d3b6efb4>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'] + movies['genre']


In [9]:
new_data = movies.drop(columns=['overview', 'genre'])



In [10]:
from sklearn.feature_extraction.text import CountVectorizer



In [11]:
cv = CountVectorizer(max_features=1000, stop_words='english')


In [12]:
vector = cv.fit_transform(new_data['tags'].values.astype('U')).toarray()


In [13]:
vector.shape



(10000, 1000)

In [14]:
from sklearn.metrics.pairwise import cosine_similarity


In [15]:
similarity = cosine_similarity(vector)



In [16]:
print(similarity)


[[1.         0.10114435 0.20851441 ... 0.11616046 0.16718346 0.09325048]
 [0.10114435 1.         0.14552138 ... 0.         0.06482037 0.        ]
 [0.20851441 0.14552138 1.         ... 0.03713907 0.1069045  0.13416408]
 ...
 [0.11616046 0.         0.03713907 ... 1.         0.04962917 0.04152274]
 [0.16718346 0.06482037 0.1069045  ... 0.04962917 1.         0.05976143]
 [0.09325048 0.         0.13416408 ... 0.04152274 0.05976143 1.        ]]


In [17]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector: vector[1])


In [19]:
for i in distance[0:5]:
  print(new_data.iloc[i[0]].title)


The Godfather
The Godfather: Part II
House of Gucci
Batman: The Killing Joke
Bomb City


In [31]:
def reccomand(movies):
  index = new_data[new_data['title'] == movies].index[0]
  distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector: vector[1])
  for i in distance[1:6]:
    print(new_data.iloc[i[0]].title)

In [32]:
reccomand('Captain America')

Captain America: The First Avenger
Team Thor
Captain America: The Winter Soldier
Ultimate Avengers: The Movie
Letters from Iwo Jima


In [35]:
import pickle

In [38]:
pickle.dump(new_data, open('movies_list.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [39]:
from google.colab import files
files.download('movies_list.pkl')
files.download('similarity.pkl')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [37]:
pickle.load(open('movies_list.pkl', 'rb'))

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                   tags  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 3 columns]